import './globals.css'
import Footer from '../components/footer/footer'
import Breadcrumb from '../components/breadcrumb/breadcrumb'
import Navigation from '../components/navigation/navigation'
import { IoMdArrowDropright } from "react-icons/io";

export const metadata = {
  title: 'Mundo Da Cozinha',
  description: 'Generated by create next'
}

export default async function RootLayout({children}) {
  return (
    <html lang='pt-br'>
      <body suppressHydrationWarning={true}>
        <Navigation />
        <main>
          <Breadcrumb homeElement={'Página Inicial'} separator={<span> {'>'} </span>}capitalizeLinks/>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
